name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for raising an issue, we will get back to you ASAP'' first issue'
        pr-message: 'Howdy! Thanks for creating your first PR to this repo, we will try to review it ASAP.'' first pr'
